services:
  - type: web
    name: obqa-backend
    runtime: docker
    plan: free
    region: singapore
    branch: deployment_1
    rootDir: Software-project-Backend
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /actuator/health
    autoDeployTrigger: commit
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOWED_ORIGINS
        sync: false
      - key: JPA_SHOW_SQL
        value: false
      - key: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
        value: 5
      - key: SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE
        value: 1
      - key: JAVA_TOOL_OPTIONS
        value: -Xms64m -Xmx320m
